export const SET_USER = 'SET_USER';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_MOVEMENTS = 'SET_MOVEMENTS';
export const SET_LAST_EXCHANGE = 'SET_LAST_EXCHANGE';
export const SET_EXCHANGES = 'SET_EXCHANGES';
